PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE Ledger(
    ID INTEGER PRIMARY KEY NOT NULL ,
    SequenceID INTEGER,
    Time INTEGER
);

CREATE TABLE Barcodes(
    Barcode TEXT PRIMARY KEY,
    LocationID Integer,
    Name TEXT,
    FOREIGN KEY (LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT  
);

CREATE TABLE LocationTypes( 
    Name TEXT PRIMARY KEY
);

CREATE TABLE Locations(
    ID INTEGER PRIMARY KEY NOT NULL,
    Name TEXT,
    Type TEXT,
    FOREIGN KEY(Type) REFERENCES LocationTypes(Name) ON UPDATE CASCADE ON DELETE RESTRICT 
);

CREATE TABLE Components(
        ID INTEGER PRIMARY KEY NOT NULL,
        ComponentHash BLOB,
        Type TEXT,
        Unique(ComponentHash)
        );

CREATE TABLE Chemicals(
    Name TEXT PRIMARY KEY,
    ComponentID Integer,
    Type TEXT,
    MolecularWeight REAL,
    Density REAL,
    CID INTEGER,
    FOREIGN KEY(ComponentID) REFERENCES Components(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Strains(
    ID INTEGER PRIMARY KEY NOT NULL,
    ComponentID INTEGER,
    Genus TEXT,
    Species TEXT,
    Strain TEXT,
    FOREIGN KEY(ComponentID) REFERENCES Components(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Attributes(
    Attribute TEXT PRIMARY KEY
);

CREATE TABLE EnvironmentAttributes(
    ID Integer PRIMARY KEY NOT NULL,
    LedgerID INTEGER,
    LocationID INTEGER,
    Attribute TEXT,
    Value Real,
    Unit TEXT,
    Time Integer,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID)ON UPDATE CASCADE ON DELETE RESTRICT, 
    FOREIGN KEY(Attribute) REFERENCES Attributes(Attribute) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT 
);

CREATE TABLE Configurations(
    ID TEXT PRIMARY KEY,
    ConfigurationHash Integer,
    InstrumentID Integer,
    FOREIGN KEY(InstrumentID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE Transfers(
    ID INTEGER PRIMARY KEY NOT NULL ,
    LedgerID INTEGER,
    Source INTEGER,
    Destination INTEGER, 
    Quantity REAL,
    Unit TEXT,
    Time Integer,
    Configuration TEXT, 
    FOREIGN KEY(Source) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(Destination) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID)ON UPDATE CASCADE ON DELETE RESTRICT,

    CHECK (Source != Destination)
);

CREATE TABLE Movements(
    ID INTEGER PRIMARY KEY NOT NULL,
    LedgerID INTEGER,
    Parent Integer,
    Child Integer,
    Time Integer, 
    FOREIGN KEY(Child) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(Parent) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID)ON UPDATE CASCADE ON DELETE RESTRICT,
    CHECK (Parent != Child) 
);

CREATE TABLE Reads(
    ID INTEGER PRIMARY KEY NOT NULL ,
    LedgerID INTEGER,
    LocationID INTEGER,
    Type TEXT,
    Value REAL,
    Unit TEXT,
    Time INTEGER,
    Configuration TEXT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID)ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(Configuration) REFERENCES Configurations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE Activity(
    ID INTEGER PRIMARY KEY NOT NULL,
    LedgerID INTEGER,
    LocationID INTEGER,
    IsActive INTEGER,
    Time INTEGER,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID)ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Locks(
    ID INTEGER PRIMARY KEY NOT NULL,
    LedgerID INTEGER,
    LocationID INTEGER,
    IsLocked INTEGER,
    Time Integer,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID)ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Tags(
    ID INTEGER PRIMARY KEY NOT NULL ,
    LedgerID INTEGER,
    Comment TEXT,
    Time INTEGER,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID)ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CachedChildSets(
    ID INTEGER PRIMARY KEY NOT NULL,
    ChildSetHash BLOB
);

CREATE TABLE CachedChildren(
    ID INTEGER PRIMARY KEY NOT NULL,
    CachedChildSetID INTEGER,
    ChildID INTEGER,
    RowIdx INTEGER,
    ColIdx INTEGER,
    FOREIGN KEY(CachedChildSetID) REFERENCES CachedChildSets(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ChildID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CachedAttributeSets(
    ID INTEGER PRIMARY KEY NOT NULL,
    AttributeSetHash BLOB

    );

CREATE TABLE CachedAttributes(
    ID INTEGER PRIMARY KEY NOT NULL,
    AttributeSetID INTEGER,
    AttributeID TEXT,
    Value REAL,
    Unit TEXT,
    FOREIGN KEY(AttributeSetID) REFERENCES CachedAttributeSets(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(AttributeID) REFERENCES Attributes(Attribute) ON UPDATE CASCADE ON DELETE RESTRICT
);
INSERT INTO "CachedAttributes" VALUES(1,2,'Temperature',25.0,'°C');
INSERT INTO "CachedAttributes" VALUES(2,2,'Pressure',1.0,'atm');
CREATE TABLE CachedStocks(
    ID INTEGER PRIMARY KEY NOT NULL,
    StockHash BLOB
);
INSERT INTO "CachedStocks" VALUES(1,7235631925074898608);
INSERT INTO "CachedStocks" VALUES(2,4886185510029658041);
INSERT INTO "CachedStocks" VALUES(3,9.38507016110039244804e+18);
CREATE TABLE CachedComponents(
        ID INTEGER PRIMARY KEY NOT NULL,
        StockID INTEGER,
        ComponentID INTEGER, 
        Quantity REAl,
        Unit TEXT,
        FOREIGN KEY(StockID) REFERENCES CachedStocks(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
        FOREIGN KEY(ComponentID) REFERENCES Components(ID) ON UPDATE CASCADE ON DELETE RESTRICT
    );

CREATE TABLE CachedContents(
    ID INTEGER PRIMARY KEY NOT NULL,
    LocationID INTEGER,
    StockID INTEGER, 
    LedgerID INTEGER,
    Cost REAL,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(StockID) REFERENCES CachedStocks(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID) ON UPDATE CASCADE ON DELETE RESTRICT
    );

CREATE TABLE CachedDescendants(
    ID INTEGER PRIMARY KEY NOT NULL,
    LocationID INTEGER,
    ChildSetID INTEGER,
    LedgerID INTEGER,
     FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ChildSetID) REFERENCES CachedChildSets(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID) ON UPDATE CASCADE ON DELETE RESTRICT
    );

CREATE TABLE CachedEnvironments(
        ID INTEGER PRIMARY KEY NOT NULL,
        LocationID INTEGER,
        AttributeSetID INTEGER,
        LedgerID INTEGER,
        FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
        FOREIGN KEY(AttributeSetID) REFERENCES CachedAttributeSets(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
        FOREIGN KEY(LedgerID) REFERENCES Ledger(ID) ON UPDATE CASCADE ON DELETE RESTRICT
    );

CREATE TABLE CachedAncestors(
    ID INTEGER PRIMARY KEY NOT NULL,
    LocationID INTEGER,
    ParentID INTEGER,
    LedgerID INTEGER,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ParentID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE CachedLockActivity(
    ID INTEGER PRIMARY KEY NOT NULL,
    LocationID INTEGER,
    IsLocked INTEGER,
    IsActive INTEGER,
    LedgerID INTEGER,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE Experiments (
    ID INTEGER PRIMARY KEY NOT NULL ,
    Name Text, 
    User TEXT,
    IsPublic INTEGER,
    Time INTEGER
);
INSERT INTO "Experiments" VALUES(1,'test_experiment','Ben',0,1738857787.933);
CREATE TABLE Runs ( 
    ID INTEGER PRIMARY KEY NOT NULL ,
    ExperimentID INTEGER, 
    LocationID INTEGER,
    Controls Text, 
    Blanks Text,
    FOREIGN KEY (ExperimentID) REFERENCES Experiments(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE Protocols( 
    ID INTEGER PRIMARY KEY NOT NULL, 
    ExperimentID INTEGER,
    Name Text,
    SequenceIDCreatedAt INTEGER,
    EstimatedTime Real,
    FOREIGN KEY (ExperimentID) REFERENCES Experiments(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    Unique(ExperimentID,Name)
);
INSERT INTO "Protocols" VALUES(1,1,'test_protocol',53,0.0);
CREATE TABLE ProtocolEnforcement(
    ID INTEGER PRIMARY KEY NOT NULL,
    ProtocolID INTEGER, 
    LedgerID INTEGER,
    IsEnforced INTEGER,
    Time INTEGER,
    FOREIGN KEY (ProtocolID) REFERENCES Protocols(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (LedgerID) REFERENCES Ledger(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);
INSERT INTO "ProtocolEnforcement" VALUES(1,1,54,1,1738857788.369);
CREATE TABLE Encumbrances( 
    ID INTEGER PRIMARY KEY NOT NULL,
    ProtocolID INTEGER,  
    FOREIGN KEY(ProtocolID) REFERENCES Protocols(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE EncumbranceCompletion(
    ID INTEGER PRIMARY KEY NOT NULL ,
    LedgerID INTEGER,
    EncumbranceID INTEGER,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LedgerID) REFERENCES Ledger(ID)ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE EncumberedTransfers( 
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    Source INTEGER,
    Destination INTEGER, 
    Quantity REAL,
    Unit TEXT,
    Configuration TEXT,
    FOREIGN KEY(Source) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(Destination) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    
    CHECK (Source != Destination)
);

CREATE TABLE EncumberedLocks(
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    LocationID INTEGER,
    IsLocked INTEGER,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE EncumberedMovements(
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    Parent INTEGER,
    Child INTEGER,
    FOREIGN KEY(Child) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(Parent) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    CHECK (Parent != Child) 
);

CREATE TABLE EncumberedEnvironments( 
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    LocationID INTEGER,
    Attribute TEXT,
    Value Real,
    Unit,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT, 
    FOREIGN KEY(Attribute) REFERENCES Attributes(Attribute) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT 
);

CREATE TABLE EncumberedActivity(
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    LocationID INTEGER,
    IsActive INTEGER,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE EncumberedCachedContents(
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    LocationID INTEGER,
    StockID INTEGER,
    Cost REAL,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(StockID) REFERENCES CachedStocks(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);
CREATE TABLE EncumberedCachedAncestors(
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    LocationID INTEGER,
    ParentID INTEGER,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ParentID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE EncumberedCachedDescendants(
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    LocationID INTEGER,
    ChildSetID INTEGER,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(ChildSetID) REFERENCES CachedChildSets(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE EncumberedCachedEnvironments(
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER,
    LocationID INTEGER,
    AttributeSetID INTEGER,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(AttributeSetID) REFERENCES CachedAttributeSets(ID) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE EncumberedCachedLockActivity(
    ID INTEGER PRIMARY KEY NOT NULL,
    EncumbranceID INTEGER, 
    LocationID INTEGER,
    IsLocked INTEGER,
    IsActive INTEGER,
    FOREIGN KEY(EncumbranceID) REFERENCES Encumbrances(ID) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY(LocationID) REFERENCES Locations(ID) ON UPDATE CASCADE ON DELETE RESTRICT
    );
COMMIT;
